services:
  search-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-busqueda-search
    ports:
      - '3001:3001'
    environment:
      PORT: 3001
      MONGODB_URI: ${MONGODB_URI:-}
      MONGODB_DB_NAME: ${MONGODB_DB_NAME:-}
      MONGODB_COLLECTION: ${MONGODB_COLLECTION:-search_results}
    restart: unless-stopped
